import * as vscode from "vscode";
import * as path from "path";

import { createLayoutSnippet } from "../snippets/layout";
import { getRouteName } from "../utils/routeParser";
import { createPageSnippet } from "../snippets/page";
import { createLoadingSnippet } from "../snippets/loading";

import {
  createRouteSnippet,
  createGetRouteSnippet,
  createPostRouteSnippet,
  createPutRouteSnippet,
  createDeleteRouteSnippet,
} from "../snippets/route";

import { createNotFoundSnippet } from "../snippets/notFound";
import { createErrorSnippet } from "../snippets/error";

import {
  createClientSnippet,
  createServerSnippet,
  createPropsSnippet,
} from "../snippets/client";

import { getComponentName } from "../utils/componentName";

export function registerSmartProvider(
  context: vscode.ExtensionContext
) {
  /*
   * TSX provider
   */
  const reactProvider =
    vscode.languages.registerCompletionItemProvider(
      "typescriptreact",
      {
        provideCompletionItems(document) {
          return provideRouteXCompletions(document);
        },
      },
      "n"
    );

  /*
   * TypeScript provider
   *
   * This is required for route.ts.
   */
  const typescriptProvider =
    vscode.languages.registerCompletionItemProvider(
      "typescript",
      {
        provideCompletionItems(document) {
          return provideRouteXCompletions(document);
        },
      },
      "n"
    );

  context.subscriptions.push(
    reactProvider,
    typescriptProvider
  );
}

function provideRouteXCompletions(
  document: vscode.TextDocument
): vscode.CompletionItem[] {
  const fileName = path.basename(
    document.fileName
  );

  const extension = path.extname(
    document.fileName
  );

  /*
   * Only allow:
   *
   * .tsx files
   * route.ts
   */
  if (
    extension !== ".tsx" &&
    fileName !== "route.ts"
  ) {
    return [];
  }

  const routeName = getRouteName(
    document.fileName
  );

  /*
   * Next.js special files
   */

  switch (fileName) {
    case "page.tsx":
      return [
        createItem(
          "nxt",
          "Next RouteX • Page",
          createPageSnippet(routeName)
        ),
      ];

    case "layout.tsx":
      return [
        createItem(
          "nxt",
          "Next RouteX • Layout",
          createLayoutSnippet(routeName)
        ),
      ];

    case "loading.tsx":
      return [
        createItem(
          "nxt",
          "Next RouteX • Loading",
          createLoadingSnippet(routeName)
        ),
      ];

    case "error.tsx":
      return [
        createItem(
          "nxt",
          "Next RouteX • Error",
          createErrorSnippet(routeName)
        ),
      ];

    case "not-found.tsx":
      return [
        createItem(
          "nxt",
          "Next RouteX • Not Found",
          createNotFoundSnippet(routeName)
        ),
      ];

    /*
     * API Route
     */

    case "route.ts":
      return [
        createItem(
          "nxt",
          "Next RouteX • GET",
          createGetRouteSnippet()
        ),

        createItem(
          "nxt",
          "Next RouteX • POST",
          createPostRouteSnippet()
        ),

        createItem(
          "nxt",
          "Next RouteX • PUT",
          createPutRouteSnippet()
        ),

        createItem(
          "nxt",
          "Next RouteX • DELETE",
          createDeleteRouteSnippet()
        ),

        createItem(
          "nxt",
          "Next RouteX • Full API Route",
          createRouteSnippet()
        ),
      ];
  }

  /*
   * Normal TSX component
   */

  const componentName =
    getComponentName(
      document.fileName
    );

  return [
    createItem(
      "nxt",
      "Next RouteX • Client Component",
      createClientSnippet(
        componentName
      )
    ),

    createItem(
      "nxt",
      "Next RouteX • Server Component",
      createServerSnippet(
        componentName
      )
    ),

    createItem(
      "nxt",
      "Next RouteX • Component with Props",
      createPropsSnippet(
        componentName
      )
    ),
  ];
}

function createItem(
  label: string,
  detail: string,
  snippet: vscode.SnippetString
): vscode.CompletionItem {
  const item =
    new vscode.CompletionItem(
      label,
      vscode.CompletionItemKind.Snippet
    );

  item.detail = detail;

  item.documentation =
    new vscode.MarkdownString(
      `**${detail}**\n\nSmart template generated by Next RouteX.`
    );

  item.insertText = snippet;

  item.filterText = "nxt";

  item.sortText = "0";

  return item;
}